### ISSUE TITLE
rtmbuildとrtmbuild2が混在している

### ISSUE THREAD

**Issue by Naoki-Hiraoka** [Takuma-Hiraoka/template_controller_rtc#1]
どちらかに統一したらどうでしょうか

https://github.com/Takuma-Hiraoka/template_controller_rtc/blob/adeec7b85ecdbac98b8b5655dc1aeab987df936d/template_controller_msgs/CMakeLists.txt#L8

https://github.com/Takuma-Hiraoka/template_controller_rtc/blob/adeec7b85ecdbac98b8b5655dc1aeab987df936d/template_controller_rtc/CMakeLists.txt#L9

https://github.com/Takuma-Hiraoka/template_controller_rtc/blob/adeec7b85ecdbac98b8b5655dc1aeab987df936d/template_controller_ros_bridge/CMakeLists.txt#L7

**Comment by Takuma-Hiraoka** [comment]
rtmbuild2に統一しました https://github.com/Takuma-Hiraoka/template_controller_rtc/commit/bf57ad123ef14f332a609df656b732ffaad18e0a
